// FLIGHTS
export const flightSearchData = {
  departure_start_date: "",
  departure_end_date: "2025-05-09",
  departure_start_time: "",
  departure_end_time: "",
  return_start_date: "",
  return_end_date: "",
  return_start_time: "",
  return_end_time: "",
  sources: ["Paris"],
  source_airport_names: ["Paris Charles de Gaulle Airport"],
  source_airport_codes: ["CDG"],
  destinations: ["Vienna"],
  destination_airport_names: ["Vienna International Airport"],
  destination_airport_codes: ["VIE"],
  class: "",
  num_of_tickets: 1,
  sort: "",
  round_trip: "False",
  preferred_airline: null,
};

export const flightSearchResultsData = {
  Outbound: [
    {
      website: "kayak",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "07:05",
        end_time: "09:00",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "17:20",
        end_time: "19:20",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "13:05",
        end_time: "15:05",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "15:00",
        end_time: "17:00",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:09/03/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "13:05",
        end_time: "15:05",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:09/03/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "15:00",
        end_time: "17:00",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:09/03/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "07:05",
        end_time: "09:00",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:09/03/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "17:20",
        end_time: "19:20",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$192",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:09/03/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Eurowings",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/EW_sq.svg",
        start_time: "16:20",
        end_time: "20:10",
        duration: "3h 50m ",
        stops: 1,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$308",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "17:55",
        end_time: "20:00",
        duration: "2h 05m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$308",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "12:25",
        end_time: "14:30",
        duration: "2h 05m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$410",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "10:05",
        end_time: "12:10",
        duration: "2h 05m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$505",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "06:30",
        end_time: "08:40",
        duration: "2h 10m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$639",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-09-03/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "03-09-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "20:25",
        end_time: "22:25",
        duration: "2h 00m",
        stops: 0,
      },
    },
  ],
  Return: [],
};
