// FLIGHTS
export const flightSearchData = {
  departure_start_date: "",
  departure_end_date: ["2025-03-09", "2025-03-10"],
  departure_start_time: "",
  departure_end_time: "",
  return_start_date: "",
  return_end_date: ["2025-03-10", "2025-03-11"],
  return_start_time: "",
  return_end_time: "",
  sources: ["Paris, France"],
  source_airport_names: ["Paris Charles de Gaulle Airport"],
  source_airport_codes: ["CDG"],
  destinations: ["Vienna"],
  destination_airport_names: ["Vienna International Airport"],
  destination_airport_codes: ["VIE"],
  class: "Economy",
  num_of_tickets: 1,
  sort: "",
  round_trip: "True",
  preferred_airline: null,
};

export const flightSearchResultsData = {
  Outbound: [
    {
      website: "kayak",
      currency: "USD",
      price: "$108",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "09:35",
        end_time: "11:30",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$108",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "15:30",
        end_time: "17:25",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$124",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "07:10",
        end_time: "09:05",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$124",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "20:10",
        end_time: "22:05",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$130",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "10:05",
        end_time: "12:00",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$130",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "07:10",
        end_time: "09:05",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$133",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "21:00",
        end_time: "22:55",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$139",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "10:05",
        end_time: "12:00",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$170",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "15:35",
        end_time: "17:30",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$175",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "15:35",
        end_time: "17:30",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$179",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/AF_sq.svg",
        start_time: "09:35",
        end_time: "11:30",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$179",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/AF_sq.svg",
        start_time: "15:30",
        end_time: "17:25",
        duration: "1h 55m ",
        stops: 0,
      },
    },
  ],
  Return: [
    {
      website: "kayak",
      currency: "USD",
      price: "$53",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Union Ivkoni",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/UNIONIVKONI.png?crop=false&width=108&height=92&fallback=buses2.png&_v=3ae8237cb608bc6dcb0e56dc90a9ce46",
        start_time: "23:59",
        end_time: "21:00",
        duration: "21h 01m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$113",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "15:00",
        end_time: "17:00",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$113",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "20:25",
        end_time: "22:25",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$113",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "13:05",
        end_time: "15:05",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$113",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "07:00",
        end_time: "09:00",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$121",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "13:05",
        end_time: "15:05",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$121",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "15:00",
        end_time: "17:00",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$121",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "07:00",
        end_time: "09:00",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$121",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "20:25",
        end_time: "22:25",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$130",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "17:55",
        end_time: "20:00",
        duration: "2h 05m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$134",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "17:20",
        end_time: "19:20",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$153",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "17:20",
        end_time: "19:20",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$174",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "06:30",
        end_time: "08:40",
        duration: "2h 10m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$210",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "12:25",
        end_time: "14:30",
        duration: "2h 05m",
        stops: 0,
      },
    },
  ],
};
