// FLIGHTS
export const flightSearchData = {
  departure_start_date: "",
  departure_end_date: ["2025-03-09", "2025-03-10"],
  departure_start_time: "",
  departure_end_time: "",
  return_start_date: "",
  return_end_date: ["2025-03-10", "2025-03-11"],
  return_start_time: "",
  return_end_time: "",
  sources: ["Paris, France"],
  source_airport_names: ["Paris Charles de Gaulle Airport"],
  source_airport_codes: ["CDG"],
  destinations: ["Vienna"],
  destination_airport_names: ["Vienna International Airport"],
  destination_airport_codes: ["VIE"],
  class: "Economy",
  num_of_tickets: 1,
  sort: "",
  round_trip: "True",
  preferred_airline: null,
};
export const flightSearchResultsData = {
  website: "kayak",
  Outbound: [
    {
      currency: "USD",
      price: "$108",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "09:35",
        end_time: "11:30",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$108",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "15:30",
        end_time: "17:25",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$124",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "07:10",
        end_time: "09:05",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$124",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "20:10",
        end_time: "22:05",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$130",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "10:05",
        end_time: "12:00",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$130",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "07:10",
        end_time: "09:05",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$133",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "21:00",
        end_time: "22:55",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$139",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "10:05",
        end_time: "12:00",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$170",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/CDG-VIE/2025-03-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "15:35",
        end_time: "17:30",
        duration: "1h 55m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$175",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "15:35",
        end_time: "17:30",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$179",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/AF_sq.svg",
        start_time: "09:35",
        end_time: "11:30",
        duration: "1h 55m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$179",
      airport1_code: "CDG",
      airport2_code: "VIE",
      airport1_name: "Charles de Gaulle International Airport",
      airport2_name: "Vienna International Airport",
      number_of_tickets: 1,
      travel_type: "Departure",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:CDG,to:VIE,departure:03/09/2025TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-03-2025",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/AF_sq.svg",
        start_time: "15:30",
        end_time: "17:25",
        duration: "1h 55m ",
        stops: 0,
      },
    },
  ],
  Return: [
    {
      website: "kayak",
      currency: "USD",
      price: "$53",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Union Ivkoni",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/UNIONIVKONI.png?crop=false&width=108&height=92&fallback=buses2.png&_v=3ae8237cb608bc6dcb0e56dc90a9ce46",
        start_time: "23:59",
        end_time: "21:00",
        duration: "21h 01m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$113",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "15:00",
        end_time: "17:00",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$113",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "20:25",
        end_time: "22:25",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$113",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "13:05",
        end_time: "15:05",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$113",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "07:00",
        end_time: "09:00",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$121",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "13:05",
        end_time: "15:05",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$121",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "15:00",
        end_time: "17:00",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$121",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "07:00",
        end_time: "09:00",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$121",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "20:25",
        end_time: "22:25",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$130",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "17:55",
        end_time: "20:00",
        duration: "2h 05m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$134",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/OS.png?crop=false&width=108&height=92&fallback=default1.png&_v=2247889502335074ad57369cd6351053",
        start_time: "17:20",
        end_time: "19:20",
        duration: "2h 00m",
        stops: 0,
      },
    },
    {
      website: "expedia",
      currency: "USD",
      price: "$153",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url:
        "https://www.expedia.com/Flights-Search?flight-type=on&leg1=from:VIE,to:CDG,departure:10/09/2024TANYT&mode=search&passengers=adults:1,infantinlap:N&trip=oneway&sortOrder=INCREASING&sortType=CHEAPEST&options=cabinclass:economy",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Austrian Airlines",
        airlines_logo:
          "https://images.trvl-media.com/media/content/expus/graphics/static_content/fusion/v0.1b/images/airlines/vector/s/OS_sq.svg",
        start_time: "17:20",
        end_time: "19:20",
        duration: "2h 0m ",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$174",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "06:30",
        end_time: "08:40",
        duration: "2h 10m",
        stops: 0,
      },
    },
    {
      website: "kayak",
      currency: "USD",
      price: "$210",
      airport1_code: "VIE",
      airport2_code: "CDG",
      airport1_name: "Vienna International Airport",
      airport2_name: "Charles de Gaulle International Airport",
      number_of_tickets: 1,
      travel_type: "Return",
      cabin_type: "economy",
      link_url: "https://www.kayak.com/flights/VIE-CDG/2024-10-09/economy/1adults?fs=fdDir=true;stops=~0&sort=price_a",
      travel_date: "09-10-2024",
      travel: {
        airlines: "Air France",
        airlines_logo:
          "https://content.r9cdn.net/rimg/provider-logos/airlines/v/AF.png?crop=false&width=108&height=92&fallback=default1.png&_v=48aae6bb98d8c51316f5918500ed39b2",
        start_time: "12:25",
        end_time: "14:30",
        duration: "2h 05m",
        stops: 0,
      },
    },
  ],
};

export const hotelSearchData = {
  location: ["Toulouse, France"],
  checkin_dates: ["2024-09-26"],
  checkout_dates: ["2024-09-27"],
  no_of_adults: 1,
  no_of_children: 0,
  min_bedrooms: 1,
  min_price: 89,
  max_price: 278,
  amenities: [],
  sort_by: "price",
};

export const hotelSearchResultsData = {
  all: [
    {
      website: "airbnb",
      currency: "USD",
      title: "Metro house 02",
      desc: "Room in Bobigny, France",
      room_desc: "1 bed · Shared bathroom",
      hotel_desc: "About this place\nEnjoy a memorable visit when you stay in this unique place.",
      amenities:
        "Lock on bedroom door\nWifi\nFree parking on premises\nDryer\nBathtub\nHigh chair\nHair dryer\nRefrigerator\nUnavailable: Carbon monoxide alarm\nCarbon monoxide alarm",
      checkin_date: "2024-09-25",
      checkout_date: "2024-09-26",
      guest: 1,
      price: "$39",
      price_details: "$39 x 1 night\n$39\nAirbnb service fee\n$7\nTaxes\n$6\nTotal\n$52",
      price_for_sort: 39,
      booking_url:
        "https://www.airbnb.com/rooms/963573600809174568?adults=1&category_tag=Tag%3A8678&enable_m3_private_room=true&photo_id=1724504567&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-26&source_impression_id=p3_1727274235_P3kklNz8ApTp5o2N&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
      pictures: [
        "https://a0.muscache.com/im/pictures/hosting/Hosting-963573600809174568/original/8db93569-c617-4959-9c36-2368a7d8b36c.jpeg?ml=true&im_w=720",
        "https://a0.muscache.com/im/pictures/afa9a0d2-cdc7-486a-a885-b0e07de560ed.jpg?ml=true&im_w=720",
        "https://a0.muscache.com/im/pictures/hosting/Hosting-963573600809174568/original/55f708f3-9fbc-46d4-bbc4-eebe761502fe.jpeg?ml=true&im_w=720",
        "https://a0.muscache.com/im/pictures/hosting/Hosting-963573600809174568/original/b8592d45-e9e5-4544-93cb-882c2e199e54.jpeg?ml=true&im_w=720",
        "https://a0.muscache.com/im/pictures/f3028021-7cd0-48cc-8b0e-63ee66bf73a6.jpg?ml=true&im_w=720",
        "https://a0.muscache.com/im/pictures/user/User-250624658/original/ec579386-5ecb-49bc-8393-1c438f7cd126.jpeg?im_w=720",
      ],
      rating: "Less than 3",
      reviews: [
        { reviewer: "Mehdi", rating: "Rating, 5 stars", review: "The stay went very well." },
        {
          reviewer: "Paula",
          rating: "Rating, 4 stars",
          review: "Tintu was very nice to us, I made it easy for us to be well.",
        },
        {
          reviewer: "Farhad",
          rating: "Rating, 2 stars",
          review:
            "Finding a parking spot was a drama. Towels were stained and dirty. Water glasses were dirty too. At our request, these glasses were replaced for new ones but they were also dirty :-|\nIn the shower in one corner there was a mold place which was actually not nice to see. I will definitely not go back next time.\nBed was nice and clean as far as I could see.",
        },
        {
          reviewer: "Maria",
          rating: "Rating, 3 stars",
          review:
            "Very well served neighborhood on the other hand very fearful. Fortunately, the accommodation is not far from the train station.\nForget a towel in the room, quickly resolved by Tintu. Shared bathroom, with a little humidity\nReally good thing to improve: There were plates, glasses, etc. On the other hand, there was no necessary products or space to clean them. Not practical!",
        },
        {
          reviewer: "Colleen",
          rating: "Rating, 5 stars",
          review:
            "Well , a shame to have had illegal fireworks during the night however it is not the fault of the owner, clean accommodation except the tray on the table (false nail to find on top) the towels should be made available and not have to search , I recommend however",
        },
        { reviewer: "Amanda", rating: "Rating, 5 stars", review: "Great stay thank you so much" },
      ],
    },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "01 Men Only- 1 bed in a 6-bed room",
    //   desc: "Room in Villejuif, France",
    //   room_desc: "6 beds · 2 shared bathrooms",
    //   hotel_desc:
    //     "Men Room!\nWelcome to Rainbow Villa!\nWe provide dorms  rooms with shared bathroom and toilet in a private Villa near Paris.\nWe have the lockers in every room.\nAn ideal, inexpensive, clean place to sleep and shower.\nFree Wi-Fi is available in all areas and is free of charge.\nShared toilets and bathrooms with shower.\nFridge, microwave onde in kitchen.\nNO COOKING！\nPillow, duvet, linen, towels all supplied.\nOur towels are small size (50cm*90cm), you can bring your own towel if you need.\nShow more",
    //   amenities:
    //     "Wifi\nExterior security cameras on property\nUnavailable: Carbon monoxide alarm\nCarbon monoxide alarm",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$27",
    //   price_details: "$27 x 1 night\n$27\nAirbnb service fee\n$5\nTaxes\n$4\nTotal\n$36",
    //   price_for_sort: 27,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/1127507542570354253?adults=1&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-26&source_impression_id=p3_1727274236_P3ThmyWIR7KGNq55&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-790589852330519644/original/1e262095-21d6-4536-9a8a-ffd3a42d4255.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-790589852330519644/original/414899b9-c6ed-40cc-b85c-84b0e21cdea2.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-790589852330519644/original/868f28ed-6a4b-4845-939b-f772cb1ba455.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-790589852330519644/original/8a16feba-160a-4bd7-b1cb-14f417151ddb.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-790589852330519644/original/9e81673d-0757-4be5-92ae-dc7bb2552d5b.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/d4530fb0-da82-46f1-ad13-0aa807a63d3a.jpg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     { reviewer: "Chihoon", rating: "Rating, 5 stars", review: "clean and easy to access place" },
    //     {
    //       reviewer: "Antoine",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Great place for short stays in Paris. Price is good for what it has. Beddings were fine and clean. Bathroom ok, toilet very clean, especially has lockers to store your valuables. Host is proactive.",
    //     },
    //     {
    //       reviewer: "Kevina Anne",
    //       rating: "Rating, 5 stars",
    //       review: "Pleasant stay, welcoming host, private space to keep your belongings",
    //     },
    //     {
    //       reviewer: "正中",
    //       rating: "Rating, 5 stars",
    //       review: "Great location for the price, great access to the city",
    //     },
    //     {
    //       reviewer: "Raotao",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Not bad, it may be a little hot sometimes, it is close to the road, there will be some noise, overall is great, the host is very friendly, helped me in the night, I appreciate her",
    //     },
    //     { reviewer: "Elias", rating: "Rating, 4 stars", review: "It was good" },
    //   ],
    // },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "Beautiful private room, Maryline and balcony",
    //   desc: "Room in Pantin, France",
    //   room_desc: "1 queen bed · Shared bathroom",
    //   hotel_desc:
    //     "About this place\nForget your worries in this spacious and serene home. It's a really good place to live. This place and a place made for people who want to return quietly after a long day. We stay in the ZEN and the SIMPLE. The room is for rent but the rest of the apartment is not. You are welcome to enjoy it with respect and harmony with me on the premises and Clyde (my pooch), a 2nd bedroom is also available on Airbnb. Samuel Lacaze Michel (fb) if needed.\n\nThe space\nAccommodation of 70 m2 and quiet. A decoration made mainly based on recovery and modification with a personal touch of Artistic! Very atypical! Bathroom with bathtub ( you will be entitled to the bath!) The kitchen is not really accessible as it is old and not very orderly. I am often there and do not want to receive bad notes about it so I prefer to limit access to guests except to take a carafe of water, put something in the fridge or make a tea. But please don't be valuable.\n The living room is large, you are invited to go there knowing that I spend most of my time there with Clyde my dog. It will happen that it is closed if I am not there because my dog will be there for him and if you arrive through the way of yourself without me already present then the doors will be closed.\n\nGuest access\nLaundry, bathroom/ toilet and balcony ( in case of good weather) are parts shared with you , the traveler(s) of the other bedroom and myself (and Clyde my dog) .\nI warn, the kitchen is not to be shared because the furniture is from the 50s and it is not always brilliant because I cook often and I prefer to avoid bad notes about it. However, I tolerate access for simple requests such as tea or putting food in the fridge. Thank you\n\nDuring your stay\nYou'll reach me right over the phone call. Also reachable by my page (fb) Samuel Lacaze Michel\n\nOther things to note\nI will always do my best to welcome you with sincerity, kindness and kindness as I naturally am. I just ask you to take into consideration that this apartment is an Airbnb rental with a total of 2 bedrooms. I do my best to welcome you to cleanliness. However, nothing remains perfect during the stay (such as the kitchen/bathroom and toilet  that are often used) . So take into account the hazards of everyday life and other occupants and please be forgiving;) In order to simplify us in many areas, I have created an same title page called here;).\ni am expecting simple and respectful hosts who know how to be discreet and honest with me about their needs and opinions. I would always be open to any facilities and arrangements.\nMy place contains a healthy energy that I like to preserve and share with others. If you're looking for chic, IT'S NOT HERE. If you are looking for simplicity then you have found!!!! 🌹\nAs far as the parking is concerned, I ask for a contribution of €10 for an entrance and an exit ONLY. I cannot guarantee comings and goings, it will be necessary to check with my schedule. Access is complicated and requires guidance and several keys.\nShow more",
    //   amenities:
    //     "City skyline view\nFast wifi – 415 Mbps\nDedicated workspace\nFree parking on premises\nElevator\nEV charger\nPaid washer – In unit\nBathtub\nUnavailable: Lock on bedroom door\nLock on bedroom door\nUnavailable: Carbon monoxide alarm\nCarbon monoxide alarm",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$56",
    //   price_details: "$56 x 1 night\n$56\nCleaning fee\n$11\nAirbnb service fee\n$12\nTaxes\n$3\nTotal\n$82",
    //   price_for_sort: 56,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/50769770?adults=1&category_tag=Tag%3A8678&enable_m3_private_room=true&photo_id=1597761276&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-26&source_impression_id=p3_1727274236_P3FxvwJTTr6YE2gQ&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/38d8365b-b4e9-4b6d-a5ca-a334f464b52d.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/c6b1f242-24be-4b4f-843f-199d35a7585b.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/3394a79b-5221-47fa-8634-f6879be33108.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/57af5e21-b885-4740-a4b7-d482e579af4b.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/7af93911-f0a4-4301-a1eb-22281f354397.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/User/original/4075abb5-f408-4e1d-93dc-f310f3def2f5.jpeg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     {
    //       reviewer: "Silje Marie",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Smooth, easy and friendly. Samuel was quick to respond to my last minute request. Great value. I felt right at home. Thanks Samuel!",
    //     },
    //     { reviewer: "Caroline", rating: "Rating, 5 stars", review: "Effective and very clean" },
    //     {
    //       reviewer: "Colette",
    //       rating: "Rating, 5 stars",
    //       review: "Welcoming host who cares about the well-being of the people he hosts.",
    //     },
    //     {
    //       reviewer: "Cassandra",
    //       rating: "Rating, 5 stars",
    //       review: "very good experience, responsive and reassuring host!\nComfortable and spacious room.",
    //     },
    //     {
    //       reviewer: "Sophie",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "A great stay with Samuel which is very welcoming. The apartment is very nice and nicely decorated, the bedding comfortable, the small balcony adjoining the room is a plus. Quiet environment. Metro nearby, and less than 20min walk to Parc de la Villette.",
    //     },
    //     { reviewer: "Maurino", rating: "Rating, 5 stars", review: "✨" },
    //   ],
    // },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "Magnificent New Studio Louvre Palais Royal",
    //   desc: "Entire rental unit in Paris, France",
    //   room_desc: "2 guests · 1 bedroom · 1 bed · 1 bath",
    //   hotel_desc:
    //     "Welcome to our sublime 17 m2 studio located on the 5th floor without elevator in the heart of Paris, close to the Louvre, numerous restaurants and the center of the City of Lights. Our studio is designed to comfortably accommodate two people and offers modern facilities to make your stay enjoyable.\n\nThe space\nStudio features:\n\nCompletely new studio: Our studio has been recently renovated to offer a luxury and modern space.\n\nCentral location: You will be ideally located to explore Paris. The Louvre, many restaurants and tourist attractions are within walking distance.\n\nKitchen Facilities: The studio is equipped with a mini fridge and microwave for preparing light meals or storing drinks and snacks.\n\nPrivate bathroom: You will have a private bathroom with a shower and toilet.\n\nAir conditioning: For your comfort, the studio is air-conditioned, allowing you to regulate the temperature according to your preferences.\n \nSmart Tv, Wi-fi\n\nA laundry room equipped with washing and drying machines, irons, and ironing boards is available free of charge in the building.\n\nWe strive to make your stay as pleasant as possible, and we are on hand to accommodate your needs and provide information on local attractions. Book now and enjoy your stay in Paris in our comfortable and well located studio.\nThe cleaning fee includes fresh linens and towels for each guest and cleaning is carried out by a professional housekeeper.\n\nGuest access\nTravellers have access to the entire flat\n\nRegistration number\n7510110004817\nShow more",
    //   amenities:
    //     "Wifi\nTV\nFree washer – In building\nFree dryer – In building\nCentral air conditioning\nHair dryer\nMicrowave",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$166",
    //   price_details: "$166 x 1 night\n$166\nCleaning fee\n$62\nTaxes\n$3\nTotal\n$231",
    //   price_for_sort: 166,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/979563633264756488?adults=1&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-26&source_impression_id=p3_1727274236_P3tafBkuq1dyuELb&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/prohost-api/Hosting-979563633264756488/original/a9c93f4f-00e6-4381-996e-f0a22c7b0f91.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/prohost-api/Hosting-979563633264756488/original/5b642b10-8d22-4b7b-906c-07db608b2d75.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/prohost-api/Hosting-979563633264756488/original/b81031ab-0dd1-4667-bca9-1d649eabef4c.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/prohost-api/Hosting-979563633264756488/original/06ba4f38-3a5a-480c-af75-8ad5be762d2e.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/prohost-api/Hosting-979563633264756488/original/4e8cbc2f-6a58-4f2c-9133-5361f91b162e.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/1dcdea8e-f9df-4fb4-a344-cd08291d067e.jpg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     {
    //       reviewer: "Valentin Marius",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Loved my time here. It was clean and in a perfect location. The host was super helpful and responsive.",
    //     },
    //     {
    //       reviewer: "Irina",
    //       rating: "Rating, 3 stars",
    //       review:
    //         "It is very inconvenient to go up with suitcases to the 5th floor, there is no elevator.\nYou can enter the bathroom with difficulties - to get to the toilet you need to get into the shower , then close the door and thus it is possible to move around the bathroom.\nThere is simply no room for a suitcase in the room.\nIt's a very long time to wait for the warm water to come from the faucet.\nOn the day of departure, there was nowhere to leave suitcases to avoid going to the airport with them around the city before leaving.\nThis place has only 1 plus - this is the location .",
    //     },
    //     {
    //       reviewer: "Vanessa",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Accommodation in perfect location. The host is very friendly and easily accessible. Early check-in costs extra and the bathroom is a little cramped. Otherwise great.",
    //     },
    //     {
    //       reviewer: "Adrian",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Great place amazing location, small but as per Paris standards. Only pain is the 6 flights of steps up to the unit. But would stay again.",
    //     },
    //     {
    //       reviewer: "Declan",
    //       rating: "Rating, 5 stars",
    //       review: "Beautiful bijoux apartment in a superb location right next to the Louvre.",
    //     },
    //     {
    //       reviewer: "Niels",
    //       rating: "Rating, 5 stars",
    //       review: "Good! Nice stay, very central!! Compact room, however, we were out every day!",
    //     },
    //   ],
    // },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "Comfortable room in bourgeois apartment",
    //   desc: "Private room in guesthouse in Saint-Ouen-sur-Seine, France",
    //   room_desc: "1 guest · 1 bedroom · 1 bed · 1 shared bath",
    //   hotel_desc:
    //     "I rent a comfortable room in a Haussmann building.\nI share common areas (kitchen, terrace, bathroom ...) with discretion and respect. I tolerate the diversity of lifestyles as long as they do not disturb the daily life of the neighbour.\n12 m2 bedroom overlooking green terrace. Double bed. Storage. Pleasant setting. Comfortable. Linens provided. Electricity and USB connections provided. Complimentary breakfast.\n\nThe space\nSpacious, elegant, clean, secure accommodation with 2 bedrooms, including that of my guests, overlooking a personal courtyard of 60 m2, an atypism in Paris!\n\nGuest access\nAll (kitchen, bathroom, kitchen, toilet, terrace, etc.)\nShow more",
    //   amenities:
    //     "Garden view\nKitchen\nWifi\nDedicated workspace\nPets allowed\nTV with DVD player\nFree washer – In unit\nFree dryer – In unit\nBathtub\nUnavailable: Carbon monoxide alarm\nCarbon monoxide alarm",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$50",
    //   price_details: "$50 x 1 night\n$50\nCleaning fee\n$22\nAirbnb service fee\n$13\nTaxes\n$8\nTotal\n$93",
    //   price_for_sort: 50,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/702507387214606333?adults=1&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-26&source_impression_id=p3_1727274236_P3t0sHMyjZ9jR8k5&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/abe0dc67-8dea-4b8d-bc8c-10b6edb1b6b5.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-702507387214606333/original/7fe3e466-d52a-4b5b-b494-8ffc6e56bfb8.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-702507387214606333/original/dd8a454d-9a18-4be8-bbd9-a128d76b0776.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-702507387214606333/original/4c72d6f3-e1e4-47d0-a0e7-9d14eacf2a22.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-702507387214606333/original/466641a2-d485-4418-bbf0-0cf0780d88cb.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/0d2abfd4-ce38-4c66-aedc-2e5c408f2cdb.jpg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     {
    //       reviewer: "Alexandre",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Had a very nice week at Greg's. The room was very clean and nice, quite close to subways and buses. Greg was always available to me.\n5/5",
    //     },
    //     {
    //       reviewer: "Jean-Baptiste",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "I recommend this accommodation which is quite well located, the host is very welcoming and takes care of his guests with small touches!",
    //     },
    //     {
    //       reviewer: "Ste",
    //       rating: "Rating, 4 stars",
    //       review:
    //         "We visited Paris for the Olympics so the location was good for us near to Stade de France. For others who want to visit tourist attractions, it is worth noting these are generally approx 50mins away (it is ~15mins walk to the nearest metro station). The neighbourhood is okay - not the poshest part of town but we felt safe wandering through it. Restaurants seem to be a lot cheaper here than near tourist hotspots. We had a comfortable stay at Greig’s place. The room is equipped with fridge, some snacks and facilities to make hot drinks.\nThe room was clean (with the exception of some old cheese in the fridge which had been missed when clearing after the previous guests). My wife and I usually stay in ‘whole place’ type Airbnbs, so it’s difficult to make a direct comparison. I’d say the common spaces were cleanish for a place that someone is living all the time.\nGreig was friendly and courteous and was very obliging in letting us store bags for a couple of hours after checkout time.",
    //     },
    //     {
    //       reviewer: "Philippe",
    //       rating: "Rating, 4 stars",
    //       review:
    //         "Correct quality of the space and cleanliness\nI just regret the change of the listing announced by the host at the last minute",
    //     },
    //     {
    //       reviewer: "Beatrice",
    //       rating: "Rating, 5 stars",
    //       review: "Cooperative host. Nice place close to public transport.",
    //     },
    //     {
    //       reviewer: "Fatima",
    //       rating: "Rating, 5 stars",
    //       review: "I had a great stay. The room was cosy and clean. It has a nice view to a nice quiet garden.",
    //     },
    //   ],
    // },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "🥈Small new studio with balcony 2022",
    //   desc: "Entire condo in Viroflay, France",
    //   room_desc: "3 guests · 1 bedroom · 1 bed · 1 bath",
    //   hotel_desc:
    //     "Studio refurbished and maintained with care.\n\nTwo steps from Viroflay Rive Droite train station and 5 min walk to all amenities.\n\nBy transport 10 min from the Palace of Versailles, 10 min from La Défense and 20 min from Paris.\n\nEasy and free parking 1 min walk from the property.\n\nPremium Simmons bedding.\n\nFiber & Wifi high-speed internet.\n\nModern amenities.\n\nForest less than 10 min walk.\n\nFamily neighborhood, lively by day and very quiet at night.\n\nThe space\nCompletely renovated in 2022.\nNew and modern equipment.\nHigh speed Internet Fiber Ethernet & Wifi.\nPremium Simmons bedding.\nSmart TV, Amazon Prime & Disney+ TV as a bonus.\nLocated a stone's throw from Viroflay Rive Droite and a 5-minute walk from all amenities.\nForest less than 10 min walk.\nFamily neighborhood, lively by day and very quiet at night.\nQuiet neighbors.\nEasy and free parking on the street adjacent to the residence. \nWasher dryer in the entrance airlock (common space) with all the necessities: laundry detergent, stain remover, softener...\n\nGuest access\nFully independent studio with bathrooms, small kitchen and south-facing balcony.\nOnly the washer dryer is located in the entrance airlock which is common area with the neighboring studio.\nThe two studios are perfectly insulated from each other by high-performance partitions and sound doors.\nShow more",
    //   amenities:
    //     "City skyline view\nKitchen\nFast wifi – 76 Mbps\nDedicated workspace\nFree driveway parking on premises – 20 spaces\nPets allowed\n32 inch HDTV with Netflix, Disney+\nElevator\nEV charger\nExterior security cameras on property",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$46",
    //   price_details: "$46 x 1 night\n$46\nCleaning fee\n$22\nAirbnb service fee\n$12\nTaxes\n$3\nTotal\n$83",
    //   price_for_sort: 46,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/568601981686131054?adults=1&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-26&source_impression_id=p3_1727274236_P3TJUxkMAk4qxyOn&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6NTY4NjAxOTgxNjg2MTMxMDU0/original/53a07bbb-0799-428e-a4c6-3f7a4d2b1fe9.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6NTY4NjAxOTgxNjg2MTMxMDU0/original/bee9c607-5e90-4b4f-be1a-1a33f5180518.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6NTY4NjAxOTgxNjg2MTMxMDU0/original/b4ad4823-0b78-4478-8b05-9780667d9389.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6NTY4NjAxOTgxNjg2MTMxMDU0/original/0abd192c-1f59-472e-9f46-d1e44f8a0610.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6NTY4NjAxOTgxNjg2MTMxMDU0/original/a0ac55d9-f1bd-4ba9-b76e-83db9520f77b.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/User-23574782/original/e72d1ea3-c094-49ab-a315-ed2b547ef685.jpeg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     {
    //       reviewer: "Bussone",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Mathieu is a very attentive host, he received me at 8 p.m. on the evening of my arrival to give me the keys to the studio . The studio is perfect , well arranged and in a very good location .\nI would highly recommend it",
    //     },
    //     {
    //       reviewer: "Richard",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Impeccable studio as advertised. Nice welcome from Mathieu who was available and gave good advice. Great stay!",
    //     },
    //     {
    //       reviewer: "Céline",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Great place with perfect bedding!! Close to transport (metro in front of the accommodation and RER C less than 500 m away) 30 minutes from the Champ de Mars and Eiffel Tower. Shops nearby;) Free parking nearby . Lovely safe neighborhood! Friendly host! In short, everything was perfect. 👍 Thank you very much 💗",
    //     },
    //     {
    //       reviewer: "Sabine",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "I really don't have much to add because the start and end of my stay was impeccable, whether it was the accommodation ,the place,m\nthe directions given by Mathieu nothing to complain about because I plan to go back very soon.\nMathieu hat don't change, see you are a very beautiful person 🙏🏿😊",
    //     },
    //     {
    //       reviewer: "Frédéric",
    //       rating: "Rating, 5 stars",
    //       review: "As advertised. The accommodation is very convenient.",
    //     },
    //     {
    //       reviewer: "Marguerite",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Very nice modern and clean studio! It's even better than the photos! Mathieu was very attentive and kind\n20/10 on all aspects ( proximity to public transport , kindness from Mathieu , convenience and cleanliness of the studio )\nThank you!",
    //     },
    //   ],
    // },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "Spacious bedroom in a recent and quiet house",
    //   desc: "Room in Versailles, France",
    //   room_desc: "2 beds · Shared bathroom",
    //   hotel_desc:
    //     "About this place\nIn Versailles, Porchefontaine district and 2 steps from the Club Hippique de Versailles (CHV) and the Golf de la Boulie (ư Club de France), large private room of 35 m2 in duplex, on the 2nd and last floor of a modern house (built in 2011) located 12 minutes' walk from the RER C, Porchefontaine train station and a 20-minute walk from Versailles Chantiers to reach Paris Montparnasse in 12 minutes.\n\nThe space\nGuests have access to their room (35 m2) under the slope, a bathroom and shower, a separate toilet.\n2 stairs are to be climbed to get to the bedroom located on the 2nd floor of the house. The second staircase is a spiral.\n\nGuest access\nGuests have access to their bedroom, bathroom, and toilet.\n\nDuring your stay\nI can answer any questions you may have.\n\nOther things to note\nFree and safe street parking in front of the house\nShow more",
    //   amenities:
    //     "Lock on bedroom door\nWifi\nDedicated workspace\nFree street parking\nHair dryer\nExterior security cameras on property\nUnavailable: Carbon monoxide alarm\nCarbon monoxide alarm",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$56",
    //   price_details: "$56 x 2 nights\n$112\nAirbnb service fee\n$20\nTaxes\n$18\nTotal\n$150",
    //   price_for_sort: 56,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/26328821?adults=1&category_tag=Tag%3A8678&children=0&enable_m3_private_room=true&infants=0&pets=0&photo_id=1596791846&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-27&source_impression_id=p3_1727274238_P3yUAvZRudoKXm78&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-26328821/original/45109e63-c890-4cf3-aaaf-3cec88350d6a.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-26328821/original/347b8657-c61f-41ef-b002-7f39b98abed7.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/0676dd52-6abc-42e7-b1a5-6d027b9c07cd.jpg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-26328821/original/16e5102d-2cff-4bc1-b683-fe04752cd236.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-26328821/original/7328ed39-531b-42b9-ab22-f7fadd6f0301.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/a8f93611-16f4-4b81-9793-b24f12911a0e.jpg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     {
    //       reviewer: "Loic",
    //       rating: "Rating, 5 stars",
    //       review: "great welcome as often specified in previous reviews. to be recommended without hesitation",
    //     },
    //     {
    //       reviewer: "Ian",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Dear Sophie,\nYou.. were… AMAZING!!! We couldn’t have asked for a nicer, hospitable and more attentive host.\nBesides the super warm welcome, great location and lovely stay, Sophie kept track of the smaller things which made this booking one to remember. The little things she did made us feel special; like the fresh and extensive breakfast each morning (bakery, juice, jam & coffee), but also our personal guide driving us around the city in her free time telling us everything about the place and where we need to be at. Her pets made us feel at home, the family was also very welcoming but still giving us our privacy and the room was exactly as described.\nJust like Sophie told us: she wants us to be treated like our mom wants us to be treated in a foreign country.\n10/10\nKusjes (kisses)\n- Ian and Yentl",
    //     },
    //     {
    //       reviewer: "国平",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "From the moment I met her, I felt close to her and felt at ease. The bread and espresso they made for breakfast was also delicious. I was able to spend 3 nights and 4 days without any inconvenience. I was surprised to be able to stay at such an exceptionally low price during the Olympics. The meeting with Sophie is one of our best memories in Paris. Thank you.",
    //     },
    //     {
    //       reviewer: "Sylt",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Despite late arrival and last-minute booking top .ophie even picked me up after I didn't find it because my phone battery was empty. Great hostess warm,sweet and great 2 rooms. Feel free to come back but then longer.",
    //     },
    //     {
    //       reviewer: "Lauren",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Thank you so much Sophie for a wonderful stay. I hope to be back one day and share a little more of your city Versailles(the best place in France in my opinion). Tell Java and Galle we miss them!\nTo anyone looking in this area, Sophie’s home is exactly as described, except better. Guest have their own loft area and it feels very private. Sophie provided a very nice portable air conditioner, one uncomfortably hot July evening. She gave us great recommendations for visiting the town center and eating a local restaurant. The bathroom and shower were very clean and private and located right next to the guest room. We stopped in Versailles to be close to the palace of Versailles and to the Roland Garros Olympic Games. The town is easy to navigate, and Sophie was always happy to help if needed. Thanks again!",
    //     },
    //     {
    //       reviewer: "欣言",
    //       rating: "Rating, 4 stars",
    //       review:
    //         "Sophie was very hospitable, the weather was cold when the visit the host welcomed us with the cake as well as hot tea and coffee, it was really cozy; the house had sophie's dog and cat, the room was tidy and clean, the design of the building floor would not be hot to sleep even when it was hot outside; the internet was smooth, about 15 minutes walk from the metro, overall recommendation",
    //     },
    //   ],
    // },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "Cabin in Paradise",
    //   desc: "Entire home in Fontenay-sous-Bois, France",
    //   room_desc: "2 guests · 1 bedroom · 1 bed · 1 bath",
    //   hotel_desc:
    //     "We welcome you to this charming independent room with its shower room. A haven of calm, a small paradise in the middle of gardens near Paris. No overlook and very quiet. Attention, there is no kitchen, no microwave or TV! Be careful, there's no lockbox! We welcome you ourselves and agree on your check-in time before 8pm. \nSee you soon!\n\nThe space\nWelcome in our family of artists. You can discover everyone's work, one is a musician, the other visual artist. The place is in the next garden and is dedicated to hosting. We take care of advising, welcoming guests to this fantastic city. Welcome to Paris !\n\nOther things to note\nSmall clarification: \nThere is no kitchen, TV or lockbox. Check-in cannot be in the middle of the night.\nShow more",
    //   amenities:
    //     "Wifi\nUnavailable: Carbon monoxide alarm\nCarbon monoxide alarm\nUnavailable: Smoke alarm\nSmoke alarm",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$56",
    //   price_details: "$56 x 2 nights\n$112\nCleaning fee\n$22\nAirbnb service fee\n$24\nTaxes\n$18\nTotal\n$176",
    //   price_for_sort: 56,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/39691132?adults=1&children=0&enable_m3_private_room=true&infants=0&pets=0&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-27&source_impression_id=p3_1727274238_P3zkfrBLNL_UQPmO&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/78cc46fa-a192-4e98-80fd-3ed9c76ab5c4.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/6462e568-1ca4-440a-9b9b-8f8ef003b0ae.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/dcfe4750-fbb7-4fd5-a8c9-4af2834da8a3.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/8140b630-8c79-4044-986d-6e9a82d3c332.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/ecb51c04-4e42-4840-92f4-f06a091f03a8.jpg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/bfdd1b88-400e-471b-a2ba-7ebe508b1bbc.jpg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     {
    //       reviewer: "Lea",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Comfortable and peaceful accommodation a short walk from Paris.\nVery welcoming and attentive hosts.\nI recommend it!",
    //     },
    //     {
    //       reviewer: "Alexandra",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Bedroom with perfect shower room: warm, cozy, pleasantly decorated and well equipped. The hosts were also very welcoming.",
    //     },
    //     {
    //       reviewer: "Marie José",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Loved my weekend (much too short) at Fanny and Thomas's place. The place is really a little corner of heaven, very quiet ,in a garden.\nAnd Fanny is sweet. Everything was perfect!\nI'll be back in Fontenay sous bois as soon as possible!",
    //     },
    //     {
    //       reviewer: "Eva",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "A very cozy room to stay quietly outside the center. Felt very quickly at my convenience, very friendly people too. Would definitely come back, thank you!",
    //     },
    //     {
    //       reviewer: "Loris",
    //       rating: "Rating, 5 stars",
    //       review: "Super quiet and pleasant place, we keep a good memory of it",
    //     },
    //     {
    //       reviewer: "Alberto",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Very nice neighborhood on the city's rails. Close to Vincennes Park.\nThe cottage is simple but furnished with love. It does not have a kitchen, but it has to make coffee or tea in the morning. It takes about 40 minutes to enter the city.\nFanny and Thomas are both very friendly.\nI recommend!",
    //     },
    //   ],
    // },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "Private room - close to Paris and Versailles",
    //   desc: "Room in Sèvres, France",
    //   room_desc: "1 bed · Shared bathroom",
    //   hotel_desc:
    //     "About this place\nA beautiful room in my spacious, comfortable apartment, equipped with a desk area and dressing room.\n\nClose to transportations: Bus 171, Metro 9, Tram T2, Line L & U.\n\nShops and restaurants are within walking distance.\n\nVersailles is a 20-minute bus ride.\nParis - Eiffel Tower 10 - 25 minutes by Metro \n\n\nGuest Access:\n- Private bedroom\n- Shower room\n- Toilet\n- Equipped kitchen (stove, oven, microwave, washing machine)\nShow more",
    //   amenities:
    //     "Garden view\nKitchen\nFast wifi – 89 Mbps\nDedicated workspace\nFree washer – In unit\nIndoor fireplace\nLuggage dropoff allowed\nHair dryer\nRefrigerator\nUnavailable: Lock on bedroom door\nLock on bedroom door",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$73",
    //   price_details: "$73 x 2 nights\n$145\nAirbnb service fee\n$26\nTaxes\n$24\nTotal\n$195",
    //   price_for_sort: 73,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/613496368130661464?adults=1&category_tag=Tag%3A8678&children=0&enable_m3_private_room=true&infants=0&pets=0&photo_id=1487006758&search_mode=regular_search&check_in=2024-09-25&check_out=2024-09-27&source_impression_id=p3_1727274238_P3SUMa0H-gjpTArR&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/3777a805-1219-4d07-84c7-63e5ac5905fa.jpg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/9e06fb47-9b4d-4ada-8e67-967dfea6917a.jpg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/e8edb1a1-e197-4fb9-9cc2-0407dbad66c5.jpg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-613496368130661464/original/3ac0c73e-fba8-4c60-aa0c-f9b2a846f403.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-613496368130661464/original/a3d788c8-7723-4c02-b7b9-f252b15a0296.jpeg?ml=true&im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/User-206849701/original/a69f7436-8dd8-447e-bf76-82f07ef02f1b.jpeg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     {
    //       reviewer: "Gilles",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Inès is very responsive and was able to find a solution to facilitate our arrival. the apartment was very clean and matched the descriptions. I recommend",
    //     },
    //     {
    //       reviewer: "Emilie",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Great, thanks for everything.\nInès is very responsive, very kind.\nthe place was nice, the perfect location.\ni'll be glad to come back.",
    //     },
    //     {
    //       reviewer: "Emile",
    //       rating: "Rating, 4 stars",
    //       review:
    //         "Ines is a very friendly host, she was really responsive. I would recommend her place for anyone who wants to stay a bit outside of Paris.",
    //     },
    //     { reviewer: "Reona", rating: "Rating, 4 stars", review: "Easy access to the Palace of Versailles" },
    //     {
    //       reviewer: "Olivier",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "ra. everything was perfect. choice of arrival. description. bedding. bedroom. bathroom. i think I'll come back.",
    //     },
    //     {
    //       reviewer: "Omar",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "ines, great host. I congratulate you. The quiet area. impeccable room. super good location. super recommend it.",
    //     },
    //   ],
    // },
    // {
    //   website: "airbnb",
    //   currency: "USD",
    //   title: "Private room in 1930s house",
    //   desc: "Room in Chatou, France",
    //   room_desc: "1 bed · Shared bathroom",
    //   hotel_desc:
    //     "About this place\nPrivate room of 12 m2 upstairs in 1930 house quietly located a 14-minute walk from Chatou train station. The ensuite bathroom is sometimes shared (if 2nd bedroom occupied). \nParis is 15 minutes by RER A from Chatou train station and the Cassiopée training center can be reached on foot in a few minutes.\nFor late arrivals on the first day (> 10pm) please contact us.",
    //   amenities:
    //     "Lock on bedroom door\nKitchen\nWifi\nHair dryer\nUnavailable: Carbon monoxide alarm\nCarbon monoxide alarm",
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   guest: 1,
    //   price: "$45",
    //   price_details: "$45 x 1 night\n$45\nAirbnb service fee\n$8\nTaxes\n$4\nTotal\n$57",
    //   price_for_sort: 45,
    //   booking_url:
    //     "https://www.airbnb.com/rooms/733852803734810960?adults=1&category_tag=Tag%3A8678&children=0&enable_m3_private_room=true&infants=0&pets=0&photo_id=1746149842&search_mode=regular_search&check_in=2024-09-26&check_out=2024-09-27&source_impression_id=p3_1727274238_P3uVnvkNe92_hbCP&previous_page_section_name=1000&federated_search_id=3ae5e6b4-b8e0-4a38-a061-646eebb8b452",
    //   pictures: [
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-733852803734810960/original/9e1b83e8-5bee-4f0c-87c4-b3103fa55c45.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-733852803734810960/original/23489ea0-f4f1-46a8-80e0-8357900de43f.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-733852803734810960/original/4d86af42-b72b-41da-95a2-23241e7a340f.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-733852803734810960/original/0312befb-51bc-488e-81c0-65edb03b40e9.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/miso/Hosting-733852803734810960/original/5396fa8e-50f7-4255-821c-98d14a363a1c.jpeg?im_w=720",
    //     "https://a0.muscache.com/im/pictures/user/b5a07f2d-16b7-463c-b044-f9389f09ec0b.jpg?im_w=720",
    //   ],
    //   rating: "Less than 3",
    //   reviews: [
    //     {
    //       reviewer: "Florence",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Perfect bedding and bathrooms. Nice and quiet environment. Pie locations are available on a wider perimeter but within walking distance.\nThanks to Géraldine for her welcome and smile",
    //     },
    //     {
    //       reviewer: "Estelle",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Géraldine and Olivier were very welcoming, their house is ideally located and in a quiet residential area. Proximity to RER A via bus. I would recommend with great pleasure.",
    //     },
    //     {
    //       reviewer: "Sol'N",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "my stay went very well. Géraldine and Olivier are attentive to give us a very nice welcome.\ni recommend without problem",
    //     },
    //     {
    //       reviewer: "Peter",
    //       rating: "Rating, 5 stars",
    //       review:
    //         "Géraldine and Olivier could not be more welcoming and allowed me to feel at home quickly. I would recommend their place without hesitation.",
    //     },
    //     {
    //       reviewer: "Coralie",
    //       rating: "Rating, 5 stars",
    //       review: "Perfect! No complaints, the hosts are flexible and available, very friendly",
    //     },
    //     { reviewer: "Derya", rating: "Rating, 5 stars", review: "Alright" },
    //   ],
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "hotelF1 Villemomble",
    //   desc: "",
    //   hotel_desc:
    //     "Located on the outskirts of Paris, hotelF1 Villemomble offers business and leisure travellers comfortable economical rooms. Recently renovated according to the #ontheroad concept, the property offers WiFi and free parking. Guests can enjoy the breakfast buffet, food ordering terminal and vending machines. In the case of late arrival between 9pm and 6am, a key dispenser is available.",
    //   distance: 11.1534195,
    //   amenities: ["breakfast", "non_smoking", "parking", "wheelchair_access"],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 0,
    //   booking_url: "https://all.accor.com/hotel/2354/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/2354_ho_00_p_230x210.jpg",
    //     "https://www.ahstatic.com/photos/2354_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$58",
    //   member_price_total: "$116",
    //   price: "$116",
    //   price_for_sort: 116,
    //   public_price_per_night: null,
    //   public_price_total: null,
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "hotelF1 Paris Saint Ouen - Marché aux Puces",
    //   desc: "",
    //   hotel_desc:
    //     "The hotelF1 Paris Saint Ouen Marché aux Puces is close to top Paris attractions like the famous Flea Market, Sacré Coeur, Moulin Rouge and Stade de France. It has been fully refurbished with the new #OnTheRoad concept and welcomes you to its 136 new Cabrio rooms with en-suite shower and WC. Private paid parking and all-you-can-eat breakfast buffet.",
    //   distance: 5.0217924,
    //   amenities: ["non_smoking", "wheelchair_access", "wifi", "pet"],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 1,
    //   booking_url: "https://all.accor.com/hotel/2539/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/2539_ho_00_p_230x210.jpg",
    //     "https://www.ahstatic.com/photos/2539_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$79",
    //   member_price_total: "$157",
    //   price: "$157",
    //   price_for_sort: 157,
    //   public_price_per_night: null,
    //   public_price_total: null,
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "ibis budget Saint Maurice",
    //   desc: "The city-center hotel is near many shops & restaurants. Paying public underground parking 50m from the hotel. Enjoy walking or cycling with vélib' along the River Marne and in Bois de Vincennes!",
    //   hotel_desc:
    //     "The ibis budget Saint Maurice hotel is located close to the Parc Floral in Paris and the Bois de Vincennes. It is 5 mi from the AccorHotels Arena and 21.8 mi from Disneyland Paris. It is just minutes from the Joinville-le-Pont train station and RER A line, which will take you to the heart of Paris passing through Nation, Gare de Lyon, Châtelet Les Halles and La Défense. The rooms are designed to accommodate up to 3 people, with A/C and WIFI in all of the rooms. Unlimited buffet breakfast at a great price!",
    //   distance: 9.1364,
    //   amenities: [
    //     "air_conditioning",
    //     "breakfast",
    //     "non_smoking",
    //     "privative_bathroom",
    //     "wheelchair_access",
    //     "wifi",
    //     "eco_certified",
    //     "pet",
    //   ],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 2,
    //   booking_url: "https://all.accor.com/hotel/2712/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/2712_ho_00_p_1024x768.jpg",
    //     "https://www.ahstatic.com/photos/2712_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$89",
    //   member_price_total: "$177",
    //   price: "$177",
    //   price_for_sort: 177,
    //   public_price_per_night: "$93",
    //   public_price_total: "$186",
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "ibis budget Gennevilliers Asnières",
    //   desc: "",
    //   hotel_desc:
    //     "Due to the health situation, your bedroom is cleaned and disinfected before your arrival. During your stay housekeeping will not access your bedroom. If you stay more than two nights a change of room is offered, subject to availability, In compliance with sanitary rules, bedrooms must be vacated no later than 10 am to afford sufficient ventilation between guests, for everyone's safety",
    //   distance: 7.4441094,
    //   amenities: ["breakfast", "parking", "wifi"],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 2,
    //   booking_url: "https://all.accor.com/hotel/3186/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/3186_ho_00_p_1024x768.jpg",
    //     "https://www.ahstatic.com/photos/3186_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$116",
    //   member_price_total: "$232",
    //   price: "$232",
    //   price_for_sort: 232,
    //   public_price_per_night: "$122",
    //   public_price_total: "$244",
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "hotelF1 Paris Porte de Chatillon",
    //   desc: "",
    //   hotel_desc:
    //     "HotelF1 Paris Porte de Châtillon is in the 14th arrondissement, and easy to get to by public transport or car. For a family weekend or a business trip, choose from our 155 Cabrio rooms with private bathrooms, part of the new concept #ontheroad by HotelF1.",
    //   distance: 4.5959716,
    //   amenities: ["breakfast", "iron", "non_smoking", "tennis", "wheelchair_access", "wifi", "pet", "parking"],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 1,
    //   booking_url: "https://all.accor.com/hotel/5010/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/5010_ho_00_p_230x210.jpg",
    //     "https://www.ahstatic.com/photos/5010_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$120",
    //   member_price_total: "$240",
    //   price: "$240",
    //   price_for_sort: 240,
    //   public_price_per_night: null,
    //   public_price_total: null,
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "ibis budget Chatillon Paris Ouest",
    //   desc: "",
    //   hotel_desc:
    //     "The ibis budget Châtillon Paris Ouest hotel is all you need at a smart price at the gates of the capital. Reception open 24/7, an attentive team and a bedroom with bathroom facilities, for a great stay. As a group or family, you can choose communicating rooms. If you're peckish, the vending machines offer hot or cold drinks and a treat. Or have a meal delivered to you via the hotel's ordering point.",
    //   distance: 8.369818,
    //   amenities: [
    //     "air_conditioning",
    //     "breakfast",
    //     "non_smoking",
    //     "wheelchair_access",
    //     "wifi",
    //     "eco_certified",
    //     "pet",
    //     "parking",
    //   ],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 2,
    //   booking_url: "https://all.accor.com/hotel/6886/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/6886_ho_00_p_1024x768.jpg",
    //     "https://www.ahstatic.com/photos/6886_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$123",
    //   member_price_total: "$246",
    //   price: "$246",
    //   price_for_sort: 246,
    //   public_price_per_night: "$137",
    //   public_price_total: "$273",
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "ibis budget Paris Porte de Pantin",
    //   desc: "Recently renovated, warm and welcoming with secure private parking, this hotel offers you all the comforts and facilities for a pleasant stay in Paris.",
    //   hotel_desc:
    //     "Close to Parc de la Villette and Zenith de Paris, the ibis budget Paris Porte de Pantin has rooms for 1 to 5 people that will meet all your needs. The team can not wait for you to experience a great stay at a low price. Discover our comfortable rooms and brand-new bedding. Enjoy our generous buffet breakfast, vending machine and free WIFI. For added comfort, the hotel offers paid and covered parking.",
    //   distance: 5.806864,
    //   amenities: [
    //     "air_conditioning",
    //     "breakfast",
    //     "child_facilities",
    //     "iron",
    //     "non_smoking",
    //     "wheelchair_access",
    //     "wifi",
    //     "parking",
    //   ],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 2,
    //   booking_url: "https://all.accor.com/hotel/3088/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/3088_ho_00_p_1024x768.jpg",
    //     "https://www.ahstatic.com/photos/3088_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$136",
    //   member_price_total: "$272",
    //   price: "$272",
    //   price_for_sort: 272,
    //   public_price_per_night: "$144",
    //   public_price_total: "$287",
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "Novotel Paris Val de Fontenay",
    //   desc: "Our hotel is just minutes from Paris by RER, and ideal for business or leisure in the Paris area. Disneyland is 25 minutes away, and there's Vincennes Zoo, and the Marne riverside 'guinguette' cafes.",
    //   hotel_desc:
    //     "Welcome to the Novotel Paris Val de Fontenay, in the Val de Fontenay business district just 50 yards from RER station lines A and E. The new hotel has 100 high-quality air-conditioned rooms, and a lounge bar for socializing, making it an ideal stopover for leisure or business, with easy links to La Defense and only 25 minutes from Disneyland Paris.",
    //   distance: 9.960858,
    //   amenities: [
    //     "air_conditioning",
    //     "bar",
    //     "breakfast",
    //     "hearing_room",
    //     "pet",
    //     "meeting_rooms",
    //     "non_smoking",
    //     "privative_bathroom",
    //     "room_service",
    //     "wheelchair_access",
    //     "wifi",
    //     "laundry",
    //   ],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 4,
    //   booking_url: "https://all.accor.com/hotel/B6S6/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/b6s6_ho_00_p_1024x768.jpg",
    //     "https://www.ahstatic.com/photos/b6s6_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$145",
    //   member_price_total: "$290",
    //   price: "$290",
    //   price_for_sort: 290,
    //   public_price_per_night: "$153",
    //   public_price_total: "$306",
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "ibis Paris Porte de Bercy",
    //   desc: "The ibis Paris Porte de Bercy Hotel is ideal for your stays at the gates of Paris. Easy access to the capital by the Liberté line 8 metro station, bus line 24 at the hotel doorstep, and tramway T3A.",
    //   hotel_desc:
    //     "The ibis Paris Porte de Bercy boasts classic, comfortable rooms with A/C. Check out our breakfast buffet's generous and varied selection as soon as you wake up. Enjoy it-it's all you can eat! For your work trips, the hotel has several fully equipped seminar rooms that can host up to 110 people. There's nothing like a good meal to unwind! Our restaurant chef has also put together a tasty, traditional menu.",
    //   distance: 4.763986,
    //   amenities: [
    //     "air_conditioning",
    //     "bar",
    //     "child_facilities",
    //     "meeting_rooms",
    //     "non_smoking",
    //     "privative_bathroom",
    //     "room_service",
    //     "wheelchair_access",
    //     "wifi",
    //     "parking",
    //   ],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 3,
    //   booking_url: "https://all.accor.com/hotel/2041/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/2041_ho_00_p_1024x768.jpg",
    //     "https://www.ahstatic.com/photos/2041_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$153",
    //   member_price_total: "$305",
    //   price: "$305",
    //   price_for_sort: 305,
    //   public_price_per_night: "$161",
    //   public_price_total: "$321",
    // },
    // {
    //   website: "accor",
    //   currency: "USD",
    //   title: "ibis Styles Paris Val de Fontenay",
    //   desc: "Our recently renovated hotel near Val de Fontenay train station has 100 rooms incl. 10 family suites. Only 15 min from Gare de Lyon and 25 min from Disneyland, it's ideal for leisure and business stays.",
    //   hotel_desc:
    //     "Our unusual hotel in Fontenay-sous-Bois welcomes you in a contemporary styled decor. From the reception to the air-conditioned rooms, the pop colors and stylish furniture liven up your stay. Breakfast and unlimited WIFI are included in all reservations at ibis Styles Paris Val de Fontenay. Adjoining the hotel, Resto Novo warmly welcomes you every day of the week.",
    //   distance: 9.879473,
    //   amenities: ["air_conditioning", "breakfast", "iron", "non_smoking", "room_service", "wheelchair_access", "wifi"],
    //   checkin_date: "2024-09-25",
    //   checkout_date: "2024-09-26",
    //   rating: 3,
    //   booking_url: "https://all.accor.com/hotel/6923/index.en.shtml",
    //   pictures: [
    //     "https://www.ahstatic.com/photos/6923_ho_00_p_1024x768.jpg",
    //     "https://www.ahstatic.com/photos/6923_ho_01_p_1024x768.jpg",
    //   ],
    //   member_price_per_night: "$158",
    //   member_price_total: "$316",
    //   price: "$316",
    //   price_for_sort: 316,
    //   public_price_per_night: "$166",
    //   public_price_total: "$332",
    // },
  ],
};
