export const filtersArray = [
  "resorts",
  "apartments",
  "homes",
  "villas",
  "inspirations",
  "destinations",
  "loyalty",
  "deals",
  "partners",
  "rides",
  "activities",
  "more",
  "all",
  "luxury",
  "premium",
  "midscale",
  "economy",
  "ennismore",
];

export const cityBreaksData = [
  {
    city: "Paris",
    price: "129",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589476/Accor/Paris_d19gry.png",
  },
  {
    city: "Budapest",
    price: "145",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589464/Accor/Budapest_ratgpc.png",
  },
  {
    city: "Seoul",
    price: "189",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589476/Accor/Seoul_yhqldi.png",
  },
  {
    city: "London",
    price: "224",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589471/Accor/London_k92ozc.png",
  },
  {
    city: "Tokyo",
    price: "267",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589469/Accor/Tokyo_fhyriz.png",
  },
  {
    city: "Kuala Lumpur",
    price: "290",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589463/Accor/Kuala_Lumpur_rakvvk.png",
  },
  {
    city: "Sydney",
    price: "311",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589468/Accor/Sydney_uoc4ej.png",
  },
  {
    city: "New York",
    price: "364",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589474/Accor/NewYork_zgo5og.png",
  },
  {
    city: "Santorini",
    price: "488",
    currency: "SGD",
    bg: "https://res.cloudinary.com/dfdqiqn98/image/upload/v1712589467/Accor/Santorini_wasljm.png",
  },
];
